---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: j5ik2o/scala-sbt-ubuntu
inputs:
  - name: tool-repo
  - name: api-repo
  - name: version-repo
  - name: application-build-cache
outputs:
  - name: to-push
  - name: updated-version-repo
  - name: notify-message
run:
  path: sh
  args:
    - tool-repo/tasks/staging/build-docker-image.sh
