---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: j5ik2o/helm
inputs:
  - name: tool-repo
  - name: api-repo
  - name: version-repo
outputs:
  - name: notify-message
run:
  dir: tool-repo
  path: sh
  args:
    - tasks/staging/deploy.sh
