---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: j5ik2o/scala-sbt-ubuntu
inputs:
  - name: tool-repo
  - name: api-repo
outputs:
  - name: to-push
run:
  path: sh
  args:
    - tool-repo/tasks/create-sbt-ivy-cache.sh
